"""Travel-led WhatsApp creative catalogue data.

Copy approval does not approve targeting, a Meta template, or sending.
"""


def option(title, when, message, button, destination, lever, guardrail):
    return {
        "title": title,
        "when": when,
        "message": message,
        "button": button,
        "destination": destination,
        "lever": lever,
        "guardrail": guardrail,
    }


SECTIONS = [
    {
        "title": "Are you flying soon?",
        "intro": "For eligible prospects with no purchase history. The question should feel timely even when exact travel dates are unknown; use genuine travel intent when it is available.",
        "items": [
            option(
                "The flying-soon question",
                "No purchase; broad travel audience or recent travel-page interest.",
                "Flying anywhere soon?\n\nThere is one small bit of travel prep that feels unnecessary right up until it does not.",
                "See the small thing",
                "A travel-led easyTag page with one clear Apple/Samsung choice.",
                "A direct, natural question opens a credible curiosity gap.",
                "Do not imply that a trip is known unless a reliable travel signal exists.",
            ),
            option(
                "The holiday countdown",
                "No purchase; seasonal holiday cohort or confirmed travel interest.",
                "Got a holiday coming up?\n\nThe suitcase is usually ready before the person packing it. This is one useful thing to add before both leave home.",
                "Add it to the list",
                "A short pre-holiday checklist leading to the relevant tracker format.",
                "Anticipation and familiar packing behaviour make the click feel useful.",
                "No false countdown, departure date, stock pressure, or delivery promise.",
            ),
            option(
                "The passport-location test",
                "No purchase; travel prospect; passport product or guide verified and available.",
                "Quick holiday test: could you put your hand on your passport in ten seconds?\n\nIf not, this may be worth seeing before the packing starts.",
                "Take the quick look",
                "A passport-travel page matched to the products currently sold.",
                "The reader performs a small self-test before easyTag is introduced.",
                "Do not claim a passport can be tracked unless the exact linked product supports it.",
            ),
            option(
                "The suitcase trust exercise",
                "No purchase; broad travel audience.",
                "A suitcase disappearing behind the check-in desk is a surprisingly large trust exercise.\n\nThere is a small way to make it feel less blind.",
                "See how",
                "A baggage tracking explainer with ecosystem choice above the fold.",
                "A vivid airport moment makes the problem instantly recognisable.",
                "Never imply airline data access, guaranteed recovery, or live baggage handling information.",
            ),
            option(
                "The calm-packing version",
                "No purchase; holiday planning or travel-content audience.",
                "Packing is mostly deciding what not to forget, then checking it all again anyway.\n\nOne part of that ritual can be made rather easier.",
                "Make it easier",
                "A mobile-first holiday packing guide featuring one suitable easyTag use.",
                "Recognition and relief, without using fear.",
                "The landing page must provide useful packing content, not a disguised catalogue.",
            ),
            option(
                "The night-before question",
                "No purchase; suitable for evergreen travel creative, not literal last-minute delivery.",
                "What is the one thing you check twice the night before a flight?\n\nThat answer usually reveals what deserves a tracker first.",
                "Match my answer",
                "A one-question travel use-case matcher.",
                "Personal reflection earns a product recommendation rather than forcing one.",
                "Do not send close to departure unless fulfilment timing is known and useful.",
            ),
            option(
                "The first-trip shortlist",
                "No purchase; travel intent known; ecosystem unknown.",
                "Before the next airport run, three things are worth making easier to find.\n\nThe first one is not always the suitcase.",
                "See the three",
                "A genuine three-item travel guide with Apple and Samsung routes.",
                "A specific list and non-obvious ranking create curiosity.",
                "The destination must reveal all three quickly and avoid unsupported claims.",
            ),
            option(
                "The trip-without-a-date",
                "No purchase; broad audience where exact travel timing is not known.",
                "You do not need a flight booked to know which travel item you would hate to misplace.\n\nThere is a neat way to make that one findable.",
                "Choose the item",
                "A travel-item selector that asks for ecosystem after use case.",
                "Travel relevance without pretending to know the recipient's plans.",
                "Do not infer travel dates, destination, airline, or airport.",
            ),
        ],
    },
    {
        "title": "Airport day, check-in and baggage",
        "intro": "For travel cohorts and airport-season campaigns. These hooks use airport rituals and baggage moments, but never suggest access to airline systems or promise recovery.",
        "items": [
            option(
                "The terminal pocket check",
                "Travel prospect; wallet or passport format available.",
                "Airport terminals have two kinds of people: the organised, and the suddenly-checking-every-pocket.\n\nWe made something for the second group.",
                "That is me",
                "One travel product page that matches the item shown in the hook.",
                "Identity and gentle humour make the message feel conversational.",
                "Do not send to a mixed collection; the destination must resolve one use case.",
            ),
            option(
                "The check-in farewell",
                "Travel audience; luggage tracker available for the confirmed ecosystem.",
                "You hand over the suitcase, watch it disappear, and quietly hope everyone knows what they are doing.\n\nA little extra visibility changes the feeling.",
                "See the travel version",
                "An ecosystem-matched luggage tracking page.",
                "Captures the emotional handover at check-in without dramatising it.",
                "Use 'visibility' only where the product page explains its real limitations.",
            ),
            option(
                "The baggage-belt lookalikes",
                "Travel audience; luggage category available.",
                "Every baggage belt contains at least six bags that look exactly like yours from twenty metres away.\n\nOne small addition makes the waiting less vague.",
                "See the addition",
                "A luggage page that demonstrates the tracker in a real bag.",
                "A visual airport truth creates instant recognition.",
                "Do not imply that the tracker visually identifies the bag unless the product does.",
            ),
            option(
                "The security-tray moment",
                "Travel audience; wallet or passport use case verified.",
                "Phone, wallet, passport, tray. Then the very quick count before walking away.\n\nThere is a calmer version of that moment.",
                "See the calmer version",
                "A focused wallet or passport use-case page.",
                "The rhythm mirrors a familiar airport action.",
                "Do not claim to prevent loss or theft; explain only the relevant finding function.",
            ),
            option(
                "The gate-change brain",
                "Travel cohort; editorial travel checklist available.",
                "You can read the gate number three times and still check it again five minutes later.\n\nAirports do strange things to otherwise sensible people.",
                "See the useful list",
                "A concise airport checklist with one relevant easyTag use.",
                "Warm recognition builds attention before the product appears.",
                "The page must continue the idea and offer genuine travel utility.",
            ),
            option(
                "The overhead-locker thought",
                "Travel cohort; carry-on or everyday-carry use case available.",
                "The overhead locker closes and your brain immediately asks whether everything important is still with you.\n\nThat question can be made easier to answer.",
                "Make it easier",
                "A carry-on travel page with a suitable, verified tracker use.",
                "A precise in-flight moment creates a strong curiosity bridge.",
                "Do not imply use during flight where device or airline rules would make that misleading.",
            ),
            option(
                "The carousel confidence check",
                "Travel audience; destination demonstrates the actual locating workflow.",
                "Before the first suitcase appears, everyone at the carousel performs the same quiet confidence check.\n\nYours can include one more useful clue.",
                "See the clue",
                "A transparent guide to what the tracker can and cannot show around baggage reclaim.",
                "Curiosity is grounded in a real airport wait.",
                "No guaranteed arrival, location precision, or airline cooperation claims.",
            ),
            option(
                "The airport coffee inventory",
                "Travel audience; lighter creative rotation.",
                "Airport coffee tastes better once you have counted the passport, phone, wallet and bag.\n\nOne of those checks can be made a little less manual.",
                "Upgrade the check",
                "A single travel use-case page with ecosystem selection.",
                "A relaxed, recognisable scene lowers the advertising feel.",
                "Keep the message occasional; do not imply the recipient is currently at an airport.",
            ),
        ],
    },
    {
        "title": "Holiday and return-journey moments",
        "intro": "For seasonal prospects, returning travellers, or lapsed customers. Ask about holidays without pretending the system knows where someone travelled.",
        "items": [
            option(
                "The recent-holiday question",
                "Broad re-engagement or travel-season audience; no exact trip data required.",
                "Been on holiday recently?\n\nThere is usually one moment on the journey home that makes a tracker suddenly seem very sensible.",
                "See the moment",
                "An editorial return-journey story with the product reveal above the fold.",
                "Invites memory and leaves one honest detail unresolved.",
                "Do not state or imply that a recent holiday is known.",
            ),
            option(
                "The hotel-room sweep",
                "Travel audience; holiday or hotel content engagement.",
                "The final hotel-room sweep always feels suspiciously incomplete.\n\nThere is one way to make the last look less theatrical.",
                "Do the calmer check",
                "A hotel checkout checklist with one verified tracker use.",
                "A highly recognisable holiday scene with light humour.",
                "The checklist must be useful even if the visitor does not buy.",
            ),
            option(
                "The unpacking discovery",
                "Returning-travel or lapsed-customer cohort.",
                "Unpacking after a holiday reveals two things: what you never used, and what you were relieved not to lose.\n\nThe second list is more interesting.",
                "See the second list",
                "An editorial list of travel items worth making findable.",
                "Post-trip reflection creates relevance without urgency.",
                "Avoid claiming knowledge of what the customer packed or lost.",
            ),
            option(
                "The next-trip improvement",
                "Returning traveller or prior travel customer; no active support issue.",
                "Every trip quietly produces a list called 'next time, do this better.'\n\nHere is one addition that takes almost no packing space.",
                "Add it for next time",
                "A compact travel product page showing real size and use.",
                "Improvement feels constructive rather than sales-led.",
                "Any size statement must be shown and verified on the page.",
            ),
            option(
                "The suitcase-at-home test",
                "Lapsed customer or broad travel audience.",
                "Your suitcase is probably easy to find today.\n\nThat makes today an excellent time to prepare it for the day it is not.",
                "Prepare it now",
                "A luggage setup and product page matched to ecosystem.",
                "A calm reversal makes preparation feel sensible.",
                "Avoid fear, theft language, or artificial travel deadlines.",
            ),
            option(
                "The souvenir nobody plans",
                "Travel-interest audience; humorous editorial destination available.",
                "The least enjoyable holiday souvenir is a story about the thing that went missing.\n\nThere is a small way to make that story less likely.",
                "See the small way",
                "A travel protection guide with careful product limitations.",
                "Humour and aversion are kept proportionate.",
                "Do not promise prevention or recovery; use only as a creative direction after compliance review.",
            ),
            option(
                "The next boarding pass",
                "Lapsed customer; 90+ days inactive; healthy previous relationship.",
                "Before the next boarding pass appears on your phone, there is one tiny travel upgrade worth knowing about.\n\nIt comes from a familiar family of brands.",
                "Meet the easy one",
                "An easy-family trust page leading to travel-relevant easyTag products.",
                "Travel anticipation combines with a restrained trust cue.",
                "The destination must state that easyTag and easyJet are separate businesses.",
            ),
        ],
    },
    {
        "title": "The easy family trust connection",
        "intro": "Use these selectively when brand recognition is the principal reason to click. The accurate relationship is that easyTag and easyJet are both members of the easy family of brands; they are separate businesses.",
        "items": [
            option(
                "The familiar easy name",
                "No purchase; broad acquisition; dedicated brand-relationship page available.",
                "You probably know the easy name from easyJet.\n\neasyTag is another member of the easy family of brands, focused on a very travel-relevant problem.",
                "Meet easyTag",
                "A plain-English easy-family relationship page with a travel product bridge.",
                "Familiarity earns the click while the product role remains intriguing.",
                "Clearly state that easyTag and easyJet are separate businesses; never imply endorsement or operation.",
            ),
            option(
                "The same-family clarification",
                "No purchase or trust-seeking visitor; suitable after brand-authenticity questions.",
                "Same easy family. Different business. Surprisingly useful at an airport.\n\nThat is easyTag in one line.",
                "Check us out",
                "A trust-first landing page citing the official easy family listing.",
                "Directness resolves suspicion without a corporate explanation.",
                "Do not use logos or wording outside the approved easy brand rules.",
            ),
            option(
                "The orange-name question",
                "Prospect who may recognise the easy brand but not easyTag.",
                "Recognise the orange easy name?\n\nYou may know it from flying. This member of the family is interested in what travels with you.",
                "See what we do",
                "An easyTag introduction page with the separate-business clarification visible.",
                "Recognition, curiosity and travel relevance arrive in two short lines.",
                "Avoid saying or suggesting that easyJet markets, endorses, owns, or supplies easyTag.",
            ),
            option(
                "The airport-side introduction",
                "Travel acquisition; dedicated easy-family explainer and product route available.",
                "The easy family is best known for getting people thinking about flights.\n\nOne of its other brands has a useful idea for the bag going with you.",
                "See the idea",
                "An easy-family explainer leading to one luggage use case.",
                "Uses broad brand history without presenting the companies as partners.",
                "Compliance must approve the exact family wording before Meta template submission.",
            ),
            option(
                "The official-family check",
                "Trust-focused audience or people who previously questioned brand legitimacy.",
                "Wondering whether easyTag is really part of the easy family? Fair question.\n\nThere is a very quick official way to check.",
                "Check the family",
                "A trust page linking to easyGroup's official brand listing.",
                "Answers a natural credibility question with verifiable evidence.",
                "The source must remain current and the page must avoid claiming easyJet endorsement.",
            ),
            option(
                "The two-easy-names",
                "Broad prospecting; brand relationship is likely to improve trust.",
                "easyJet and easyTag share more than the first four letters.\n\nBoth are members of the easy family of brands, solving very different parts of a journey.",
                "See our part",
                "A relationship explainer followed by easyTag's travel use case.",
                "A clear fact creates trust while preserving product curiosity.",
                "Do not describe a commercial partnership, endorsement, shared operations, or shared customer data.",
            ),
            option(
                "The family-not-partnership note",
                "Highly trust-sensitive audience; educational creative rather than primary campaign.",
                "A useful distinction: easyTag and easyJet are separate businesses in the same easy family of brands.\n\nHere is where easyTag fits into the travel picture.",
                "See where we fit",
                "A precise easyGroup/easyJet/easyTag relationship explainer.",
                "Radical clarity can build stronger trust than implied association.",
                "Keep this wording factual and update it if the official easyGroup listing changes.",
            ),
        ],
    },
    {
        "title": "Apple travellers",
        "intro": "For recipients whose Apple ecosystem is reliably known. Keep the creative rooted in travel and use Find My language only where the linked product is verified as compatible.",
        "items": [
            option(
                "The Find My packing list",
                "Confirmed Apple user; no matching travel tracker purchase.",
                "Your holiday packing list may already have an app.\n\nThe interesting question is what you want to appear inside Find My before check-in.",
                "Build the list",
                "An Apple travel selector organised by luggage, wallet and passport use cases.",
                "The familiar app becomes part of the packing ritual.",
                "Verify Find My compatibility for every product shown.",
            ),
            option(
                "The suitcase in Find My",
                "Confirmed Apple user; luggage product available and not already owned.",
                "There is something reassuring about seeing the suitcase you just checked in appear somewhere familiar.\n\nFor iPhone users, the route starts in Find My.",
                "See the route",
                "An honest Apple luggage-tracking guide.",
                "Familiar interface plus airport emotion lowers complexity.",
                "Explain location limitations and never guarantee baggage recovery.",
            ),
            option(
                "The wallet before boarding",
                "Confirmed Apple user; no Apple-compatible wallet card purchase.",
                "Before boarding: phone, passport, wallet.\n\nOne of those can sit quietly inside Find My without changing shape very much.",
                "See which one",
                "The verified Apple-compatible wallet card page.",
                "A compact reveal grounded in an airport checklist.",
                "Any size or shape claim must be demonstrated honestly.",
            ),
            option(
                "The Apple travel shortcut",
                "Confirmed Apple user; comparing tracker formats.",
                "Card, tag or travel cover?\n\nFor an iPhone traveller, the useful answer depends mostly on where it needs to live.",
                "Choose the shape",
                "A format comparison limited to verified Apple-compatible products.",
                "Simplifies the choice around the trip, not technical specifications.",
                "Comparison facts and current stock must be verified.",
            ),
            option(
                "The easy-family Apple route",
                "Confirmed Apple user; trust-led travel acquisition.",
                "You may know the easy name from easyJet.\n\nAnother member of the easy family has made a travel-friendly route into Apple's Find My network.",
                "See the Apple route",
                "An easy-family explainer leading to verified Apple-compatible easyTag products.",
                "Combines brand trust, ecosystem relevance and travel purpose.",
                "State that easyTag and easyJet are separate businesses and verify all Apple claims.",
            ),
        ],
    },
    {
        "title": "Samsung travellers",
        "intro": "For recipients whose Samsung ecosystem is reliably known. Treat Samsung as the primary route, not an afterthought to Apple.",
        "items": [
            option(
                "The Samsung holiday route",
                "Confirmed Samsung user; no matching travel product purchase.",
                "Planning a holiday with a Samsung phone?\n\nThere is a wallet-sized travel idea that does not ask you to switch sides.",
                "See the Samsung one",
                "The verified Samsung-compatible wallet tracker page.",
                "Ecosystem recognition removes a common compatibility concern.",
                "Verify the exact Samsung models, region and app requirements.",
            ),
            option(
                "The baggage-network surprise",
                "Confirmed Samsung user; travel audience.",
                "AirTags get most of the travel stories, but Samsung phones have their own finding network.\n\nThat matters when the suitcase leaves the check-in desk.",
                "See how it works",
                "A Samsung travel explainer with current SmartThings Find terminology.",
                "A useful surprise directly connects the ecosystem to an airport moment.",
                "No claims about airline integration, guaranteed tracking, or unsupported network coverage.",
            ),
            option(
                "The Samsung-only packing list",
                "Confirmed Samsung user; multiple formats available.",
                "We removed the Apple options and the vague 'works with Android' claims.\n\nThis is the Samsung-only travel list.",
                "Open the list",
                "A Samsung-filtered travel page that cannot reset to mixed products.",
                "Clarity and respect for the recipient's device build trust.",
                "Every listed product must have explicit, current Samsung compatibility.",
            ),
            option(
                "The SmartThings airport question",
                "Confirmed Samsung user; no matching wallet or luggage product.",
                "If you could add one airport item to SmartThings Find, which would it be?\n\nThe wallet answer is unexpectedly neat.",
                "See the wallet answer",
                "A verified Samsung wallet product demonstration.",
                "A self-question and physical reveal make the click natural.",
                "Use SmartThings Find language only as supported by the current instructions.",
            ),
            option(
                "The easy-family Samsung route",
                "Confirmed Samsung user; trust-led travel acquisition.",
                "The easy name may remind you of flying.\n\neasyTag is another member of the easy family, with a travel idea made for Samsung users too.",
                "See the Samsung route",
                "An easy-family explainer leading to verified Samsung-compatible products.",
                "Brand familiarity reassures an audience often overlooked by tracker advertising.",
                "State that easyTag and easyJet are separate businesses and verify all Samsung claims.",
            ),
        ],
    },
    {
        "title": "Existing owners and previous buyers",
        "intro": "For customers whose first purchase has been delivered and is healthy. Travel creates a natural reason to use the product better or explore one genuinely complementary category.",
        "items": [
            option(
                "The pre-flight test run",
                "Existing owner; no active support issue; travel season or travel intent.",
                "Flying soon? Test your easyTag once while the bag is still beside you.\n\nIt makes the airport version much less mysterious.",
                "Do the test",
                "A model-specific pre-travel test guide.",
                "Immediate owner value comes before any cross-sell.",
                "Instructions must match the purchased product and phone ecosystem.",
            ),
            option(
                "The second travel item",
                "Existing owner; first product healthy; another travel category remains unowned.",
                "You have already made one thing easier to find.\n\nBefore the next flight, what is the second item you would least like to lose sight of?",
                "Match the second item",
                "A travel use-case selector excluding all owned products.",
                "A self-test earns a complementary recommendation.",
                "Purchase exclusions must account for variants, bundles and duplicate SKUs.",
            ),
            option(
                "The owner airport checklist",
                "Existing owner; useful pre-travel engagement; no complaint or return.",
                "Your easyTag has one job before the airport: prove it is ready while you still know where everything is.\n\nHere is the ten-second check.",
                "Run the check",
                "A product-specific readiness check.",
                "Practical reassurance strengthens the ownership experience.",
                "Do not invent battery, maintenance, or connectivity steps.",
            ),
            option(
                "The post-holiday owner habit",
                "Existing owner; returning-travel season or 30+ days after purchase.",
                "Back from holiday? Before the suitcase disappears into storage, there is one useful tracker check worth doing.\n\nFuture you will approve.",
                "Do the useful check",
                "A verified care or readiness guide for the exact product.",
                "Post-trip timing gives a boring maintenance step a human reason.",
                "Do not imply a holiday is known; phrase as a question unless travel data is explicit.",
            ),
            option(
                "The easy-family owner story",
                "Existing owner; healthy experience; suitable for brand affinity rather than immediate sales.",
                "You already know easyTag. You may know the wider easy family from easyJet.\n\nThe connection is real, but probably not quite what you think.",
                "See the family story",
                "A precise relationship explainer citing easyGroup's official brand listing.",
                "Owners are invited into the brand story through an honest open loop.",
                "Explain the separate-business relationship clearly and avoid endorsement language.",
            ),
        ],
    },
    {
        "title": "Resolved inbox contacts and gentle re-entry",
        "intro": "For people who contacted the business and whose issue is fully resolved. Use a cooling period and never expose private support details in marketing copy.",
        "items": [
            option(
                "The resolved-contact holiday question",
                "Previous inbox contact; issue resolved; at least seven days later; no complaint or refund.",
                "Are you going on holiday this year?\n\nWe made a very short guide to the things travellers most wish they could find faster.",
                "Read the short guide",
                "A genuinely short travel guide with ecosystem-matched routes.",
                "A normal question reopens the conversation without referring to support history.",
                "Never send while a conversation is unresolved, escalated, refunded or negative.",
            ),
            option(
                "The airport problem we hear",
                "Previous inbox contact; resolved; travel guide available.",
                "One airport question comes up more than you might expect: what is actually worth tracking?\n\nThe useful answer fits on one page.",
                "See the answer",
                "A one-page travel use-case guide.",
                "Sounds like practical help rather than a catalogue message.",
                "Do not claim support-volume evidence unless it can be substantiated; revise to 'a useful question' if needed.",
            ),
            option(
                "The no-grand-announcement travel note",
                "Previous inbox contact; resolved; longer cooling period.",
                "No grand announcement. Just a useful airport thought before your next trip.\n\nThe bag you hand over can be a little less invisible.",
                "See the thought",
                "An honest luggage tracking explainer.",
                "Understatement disarms the expectation of a promotion.",
                "No airline integration, guaranteed location, or recovery claims.",
            ),
            option(
                "The trust-first reintroduction",
                "Previous contact; resolved; did not purchase; brand trust may be a barrier.",
                "You may recognise our easy name from easyJet.\n\neasyTag is part of the same easy family of brands, built as a separate business for the things travelling with you.",
                "Check us out",
                "An easy-family relationship page followed by one travel use case.",
                "A factual trust cue gives the recipient a reason to reconsider the brand.",
                "Use only after brand/compliance approval; clearly explain the separate-business relationship.",
            ),
            option(
                "The post-support useful list",
                "Previous contact; resolved; no recent campaign using the same hook.",
                "Before the next airport run, there are four things worth checking and only one is on the boarding pass.\n\nThis is the useful list.",
                "Open the list",
                "A four-item airport checklist with one relevant easyTag bridge.",
                "A numbered promise and airport relevance create a clean click motive.",
                "The page must show exactly four useful checks and avoid mentioning the support conversation.",
            ),
        ],
    },
]


assert sum(len(section["items"]) for section in SECTIONS) == 50
